//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChatServiceReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChatServiceReference.Message))]
    public partial class BaseEntity : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class User : ChatServiceReference.BaseEntity
    {
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Message : ChatServiceReference.BaseEntity
    {
        
        private ChatServiceReference.User ReceiverField;
        
        private ChatServiceReference.User SenderField;
        
        private string TextField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChatServiceReference.User Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChatServiceReference.User Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatService", CallbackContract=typeof(ChatServiceReference.IChatServiceCallback))]
    public interface IChatService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Join", ReplyAction="http://tempuri.org/IChatService/JoinResponse")]
        System.Threading.Tasks.Task JoinAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Leave", ReplyAction="http://tempuri.org/IChatService/LeaveResponse")]
        System.Threading.Tasks.Task LeaveAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/SendMessage", ReplyAction="http://tempuri.org/IChatService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(ChatServiceReference.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetUsers", ReplyAction="http://tempuri.org/IChatService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.User>> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetMessages", ReplyAction="http://tempuri.org/IChatService/GetMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.Message>> GetMessagesAsync(ChatServiceReference.User user1, ChatServiceReference.User user2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IChatServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/ReceiveMessage")]
        void ReceiveMessage(ChatServiceReference.Message message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UserJoined")]
        void UserJoined(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IChatServiceChannel : ChatServiceReference.IChatService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ChatServiceClientBase : System.ServiceModel.DuplexClientBase<ChatServiceReference.IChatService>, ChatServiceReference.IChatService
    {
        
        public ChatServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task JoinAsync(string user)
        {
            return base.Channel.JoinAsync(user);
        }
        
        public System.Threading.Tasks.Task LeaveAsync(string user)
        {
            return base.Channel.LeaveAsync(user);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(ChatServiceReference.Message msg)
        {
            return base.Channel.SendMessageAsync(msg);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.User>> GetUsersAsync()
        {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.Message>> GetMessagesAsync(ChatServiceReference.User user1, ChatServiceReference.User user2)
        {
            return base.Channel.GetMessagesAsync(user1, user2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IMauiChatService")]
    public interface IMauiChatService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMauiChatService/MauiJoin", ReplyAction="http://tempuri.org/IMauiChatService/MauiJoinResponse")]
        System.Threading.Tasks.Task MauiJoinAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMauiChatService/MauiLeave", ReplyAction="http://tempuri.org/IMauiChatService/MauiLeaveResponse")]
        System.Threading.Tasks.Task MauiLeaveAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMauiChatService/MauiSendMessage", ReplyAction="http://tempuri.org/IMauiChatService/MauiSendMessageResponse")]
        System.Threading.Tasks.Task MauiSendMessageAsync(ChatServiceReference.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMauiChatService/MauiGetUsers", ReplyAction="http://tempuri.org/IMauiChatService/MauiGetUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.User>> MauiGetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMauiChatService/MauiGetMessages", ReplyAction="http://tempuri.org/IMauiChatService/MauiGetMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.Message>> MauiGetMessagesAsync(ChatServiceReference.User user1, ChatServiceReference.User user2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMauiChatServiceChannel : ChatServiceReference.IMauiChatService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MauiChatServiceClient : System.ServiceModel.ClientBase<ChatServiceReference.IMauiChatService>, ChatServiceReference.IMauiChatService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MauiChatServiceClient() : 
                base(MauiChatServiceClient.GetDefaultBinding(), MauiChatServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMauiChatService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MauiChatServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MauiChatServiceClient.GetBindingForEndpoint(endpointConfiguration), MauiChatServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MauiChatServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MauiChatServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MauiChatServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MauiChatServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MauiChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task MauiJoinAsync(string user)
        {
            return base.Channel.MauiJoinAsync(user);
        }
        
        public System.Threading.Tasks.Task MauiLeaveAsync(string user)
        {
            return base.Channel.MauiLeaveAsync(user);
        }
        
        public System.Threading.Tasks.Task MauiSendMessageAsync(ChatServiceReference.Message msg)
        {
            return base.Channel.MauiSendMessageAsync(msg);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.User>> MauiGetUsersAsync()
        {
            return base.Channel.MauiGetUsersAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ChatServiceReference.Message>> MauiGetMessagesAsync(ChatServiceReference.User user1, ChatServiceReference.User user2)
        {
            return base.Channel.MauiGetMessagesAsync(user1, user2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMauiChatService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMauiChatService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfService/ChatService/maui");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MauiChatServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMauiChatService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MauiChatServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMauiChatService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMauiChatService,
        }
    }
    
    public class ReceiveMessageReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public ReceiveMessageReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ChatServiceReference.Message message
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ChatServiceReference.Message)(this.results[0]));
            }
        }
    }
    
    public class UserJoinedReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public UserJoinedReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public string username
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public partial class ChatServiceClient : ChatServiceClientBase
    {
        
        public ChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new ChatServiceClientCallback(), binding, remoteAddress)
        {
        }
        
        private ChatServiceClient(ChatServiceClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<ReceiveMessageReceivedEventArgs> ReceiveMessageReceived;
        
        public event System.EventHandler<UserJoinedReceivedEventArgs> UserJoinedReceived;
        
        private void OnReceiveMessageReceived(object state)
        {
            if ((this.ReceiveMessageReceived != null))
            {
                object[] results = ((object[])(state));
                this.ReceiveMessageReceived(this, new ReceiveMessageReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnUserJoinedReceived(object state)
        {
            if ((this.UserJoinedReceived != null))
            {
                object[] results = ((object[])(state));
                this.UserJoinedReceived(this, new UserJoinedReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class ChatServiceClientCallback : object, IChatServiceCallback
        {
            
            private ChatServiceClient proxy;
            
            public void Initialize(ChatServiceClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void ReceiveMessage(ChatServiceReference.Message message)
            {
                this.proxy.OnReceiveMessageReceived(new object[] {
                            message});
            }
            
            public void UserJoined(string username)
            {
                this.proxy.OnUserJoinedReceived(new object[] {
                            username});
            }
        }
    }
}
